version: "3.7"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: belajar_api
        container_name: belajar_api-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - belajar_api

    app_queue:
        build:
            context: ./
            dockerfile: Dockerfile
        image: belajar_api
        container_name: belajar_api-app-queue
        restart: always
        command: php artisan queue:work
        depends_on:
            - app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - belajar_api

    app_cron:
        build:
            context: ./
            dockerfile: Dockerfile
        image: belajar_api
        container_name: belajar_api-app-cron
        restart: always
        command: php artisan schedule:work
        depends_on:
            - app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - belajar_api

    # db:
    #     image: postgres:14.1-alpine
    #     container_name: belajar_api-db
    #     restart: always
    #     environment:
    #         POSTGRES_DB: ${DB_DATABASE}
    #         POSTGRES_USER: ${DB_USERNAME}
    #         POSTGRES_PASSWORD: ${DB_PASSWORD}
    #     networks:
    #         - belajar_api
    #     ports:
    #         - "5432:5432"

    db_mysql:
        image: mysql:latest
        container_name: belajar_api-db-mysql
        restart: always
        networks:
            - belajar_api
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d

    nginx:
        image: nginx:1.17-alpine
        container_name: belajar_api-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            belajar_api:
                aliases:
                    - api.test

networks:
    belajar_api:
        driver: bridge

volumes:
    db:
        driver: local
